#+title: Today i learned

We can also name it ~Mini articles~

** 2025
*** Access google email as RSS
- Create app password using following link: https://myaccount.google.com/apppasswords
#+begin_src shell
  curl -u "Username:App password" https://mail.google.com/mail/feed/atom
#+end_src
If you email is **emacs@gmail.com** and app password generated by google is **emacs is awesome**
#+begin_src shell
    curl -u "emacs:emacs is awesome" https://mail.google.com/mail/feed/atom
#+end_src

*** Google colab to finetune llm
During the Foss United March 2025 meetup i came to know that llm can
be finetuned using google colab. 
- https://github.com/poloclub/Fine-tuning-LLMs

*** Open DNS family shield - Make internet browsing safer for whole family
- https://www.opendns.com/setupguide/#familyshield
- Blocks most of the adult websites
#+begin_example
208.67.222.123, 208.67.220.123
#+end_example

*** Emacs Copy, Cut (Kill), Paste (Yank) Trick
- Assume you want to copy or cut part of a paragraph, but not the entire thing.
- Go to the start of the text you want to select and press C-space twice.
- Then, move to the end of the text you want to operate on and press C-w to cut (kill) or M-w to copy.
- This method works in reverse as well, which is quite interesting.
- Normally, I select the text I want and then press the copy or cut command, but this approach changes the way you do it completely.

*** CSS before trick
- If you need to add any whitespace before text use the below logic
#+begin_src css
  h2 {
    text-decoration: underline;
  }

  h2.space::after {
    content: " ";
    white-space: pre;
  }
#+end_src
