#+title: Cheap storage server options
#+subtitle: cheap storage server option you can get in india
#+date: <2025-12-03 Wed>
#+author: Gold Ayan

The cheapest storage server/device you can use in home is mobile
phone(smart phone) connected to hard disk via USB-C. If your phone
supports SD card use that too.

Second option if you have a old laptop lying around, change the hard
disk and a external hdd. You can use it as a storage server as well as
media server.

If you have old business class laptop then it might have DVD disk
which can be replaced with HDD.

If you are on tight budget and have no old pc lying around the good
way to start is buying second hand PC. I personally prefare Mini pc
which are easy to carry around in travel and power draw is very
minimal compared to PC.

If you are planning to use SSD for storage, keep below points in your
mind.

*** SSD gotcha
- Unpowered SSD slowly lose data
- Don't use SSSD as backup
  
*** Second hand hard disk
- Buy SATA hard disk which is what typically used in PC not SAS (SAS is different)
- There is website called [[https://serverpartdeals.com/][Server part deals]] which provides second hard
  disk. which is recommanded by many youtubers who do selfhosting
  - Refurbished (Third party provider)
  - Recertified (By the same company)
- Sweet spot is 12-16 terabyte.
- Server part deals does provide shipping to India which is great but
  when we include tax the price will be doubled.
- In india we have following options OLX, Amazon, .. but i don't feel
  like using their service better buy a new 4TB hard disk wich will be
  sufficient for most of the case.

*** Health of hdd, sdd
- Use S.M.A.R.T to measure the health of a device, predict possible
  device failure, and provide notifications on unsafe values.
- S.M.A.R.T. (Self-Monitoring, Analysis, and Reporting Technology)  
- More info on https://wiki.archlinux.org/title/S.M.A.R.T.

Above methods are just for storing data. If you need to backup stuff

*** 321 backup technique
- 3 Copies of Data – Maintain three copies of data—the original, and
  at least two copies.
- 2 Different Media – Use two different media types for storage. This
  can help reduce any impact that may be attributable to one specific
  storage media type. It’s your decision as to which storage medium
  will contain the original data and which will contain any of the
  additional copies.
- 1 Copy Offsite – Keep one copy offsite to prevent the possibility of
  data loss due to a site-specific failure.
- Ref: https://www.seagate.com/in/en/blog/what-is-a-3-2-1-backup-strategy/
